PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
SELECT ?name#test
WHERE {
  # find members in the Strategic Forces subcommittee
  <http://www.rdfabout.com/rdf/usgov/congress/committees/SenateArmedServices/StrategicForces>
    foaf:member ?member .
  OPTIONAL {
    # find out if this same member is in the Personnel
    # subcommittee - but call him/her something different
    # (?member2)
    <http://www.rdfabout.com/rdf/usgov/congress/committees/SenateArmedServices/Personnel>
      foaf:member ?member2 .
    FILTER (?member2 = ?member) .
  }
  # keep only those rows that failed to find a ?member2
  # (member of Personnel subcommittee)
  FILTER (!bound(?member2)) .
  ?member foaf:name ?name .
}