monthsFolder = "/home/mkroetzsch/querydata/months"
queryReferenceDirectory = "/home/mkroetzsch/querydata/queryTypeReferenceFolder"
fdupesExecutable = "/home/mkroetzsch/querydata/utility/fdupes"
dbLocation = "/home/mkroetzsch/querydata/months/uniqueQueryMap.db"
queryTypeMapDbLocation = "/home/mkroetzsch/querydata/months/queryTypeMap.db"
